import pdt1 from "../assets/products/product-2.png";
import pdt2 from "../assets/products/product-7.png";
import pdt3 from "../assets/products/product-8.png";
import pdt4 from "../assets/products/product-10.png";
import pdt5 from "../assets/products/product-9.png";

export const products = [
  {
    id: "1",
    productName: "Loveseat Sofa",
    description: "A fluffy sofa",
    price: "$199.00",
    image: pdt1,
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    reviews: 4,
    new: "-50%",
    favorite: false,
    measurement: "",
    color: ["grey"],
    category: ["living room"],
    sku: 118,
    moreInfo: "The design makes it easy to put the tray back after use.",
    width: "",
    height: "",
    weight: "",
    length: "",
    package: "",
  },
  {
    id: "258",
    productName: "table lamp",
    description: "A side bed lamp",
    price: "$24.99",
    image: pdt2,
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    reviews: 3,
    new: "-50%",
    favorite: false,
    measurement: "",
    color: ["gold"],
    category: ["living room", "bedroom"],
    sku: 110,
    moreInfo: "The design makes it easy to put the tray back after use.",
    width: "",
    height: "",
    weight: "",
    length: "",
    package: "",
  },
  {
    id: "341",
    productName: "beige table lamp",
    description: "A side lamp",
    price: "$25.00",
    image: pdt3,
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    reviews: 4,
    new: "-50%",
    favorite: false,
    measurement: "",
    color: ["grey", "beige"],
    category: ["bedroom","living room"],
    sku: 247,
    moreInfo: "The design makes it easy to put the tray back after use.",
    width: "",
    height: "",
    weight: "",
    length: "",
    package: "",
  },
  {
    id: "573",
    productName: "bamboo basket",
    description: "A basket",
    price: "$195.00",
    image: pdt4,
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    reviews: 4,
    new: "-50%",
    favorite: false,
    measurement: "",
    color: ["grey"],
    category: ["living room"],
    sku: 148,
    moreInfo: "The design makes it easy to put the tray back after use.",
    width: "",
    height: "",
    weight: "",
    length: "",
    package: "",
  },
  {
    id: "13",
    productName: "kitchen stool",
    description: "A fluffy sofa",
    price: "$30.00",
    image: pdt5,
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    reviews: 4,
    new: "-50%",
    favorite: false,
    measurement: "",
    color: ["grey"],
    category: ["living room", "kitchen"],
    sku: 138,
    moreInfo: "The design makes it easy to put the tray back after use.",
    width: "",
    height: "",
    weight: "",
    length: "",
    package: "",
  },
  {
    id: "144",
    productName: "Loveseat Sofa",
    description: "A fluffy sofa",
    price: "$199.00",
    image: "",
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    reviews: 4,
    new: "-50%",
    favorite: false,
    measurement: "",
    color: ["grey"],
    category: ["living room"],
    sku: 118,
    moreInfo: "The design makes it easy to put the tray back after use.",
    width: "",
    height: "",
    weight: "",
    length: "",
    package: "",
  },
  {
    id: "157",
    productName: "Loveseat Sofa",
    description: "A fluffy sofa",
    price: "$199.00",
    image: "",
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    reviews: 4,
    new: "-50%",
    favorite: false,
    measurement: "",
    color: ["grey"],
    category: ["living room"],
    sku: 118,
    moreInfo: "The design makes it easy to put the tray back after use.",
    width: "",
    height: "",
    weight: "",
    length: "",
    package: "",
  },
  {
    id: "585",
    productName: "Loveseat Sofa",
    description: "A fluffy sofa",
    price: "$199.00",
    image: "",
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    reviews: 4,
    new: "-50%",
    favorite: false,
    measurement: "",
    color: ["grey"],
    category: ["living room"],
    sku: 118,
    moreInfo: "The design makes it easy to put the tray back after use.",
    width: "",
    height: "",
    weight: "",
    length: "",
    package: "",
  },
  {
    id: "744",
    productName: "Loveseat Sofa",
    description: "A fluffy sofa",
    price: "$199.00",
    image: "",
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    reviews: 4,
    new: "-50%",
    favorite: false,
    measurement: "",
    color: ["grey"],
    category: ["living room"],
    sku: 118,
    moreInfo: "The design makes it easy to put the tray back after use.",
    width: "",
    height: "",
    weight: "",
    length: "",
    package: "",
  },
  {
    id: "155",
    productName: "Loveseat Sofa",
    description: "A fluffy sofa",
    price: "$199.00",
    image: "",
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    reviews: 4,
    new: "-50%",
    favorite: false,
    measurement: "",
    color: ["grey"],
    category: ["living room"],
    sku: 118,
    moreInfo: "The design makes it easy to put the tray back after use.",
    width: "",
    height: "",
    weight: "",
    length: "",
    package: "",
  },
  {
    id: "238",
    productName: "Loveseat Sofa",
    description: "A fluffy sofa",
    price: "$199.00",
    image: "",
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    reviews: 4,
    new: "-50%",
    favorite: false,
    measurement: "",
    color: ["grey"],
    category: ["living room"],
    sku: 118,
    moreInfo: "The design makes it easy to put the tray back after use.",
    width: "",
    height: "",
    weight: "",
    length: "",
    package: "",
  },
  {
    id: "182",
    productName: "Loveseat Sofa",
    description: "A fluffy sofa",
    price: "$199.00",
    image: "",
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    reviews: 4,
    new: "-50%",
    favorite: false,
    measurement: "",
    color: ["grey"],
    category: ["living room"],
    sku: 118,
    moreInfo: "The design makes it easy to put the tray back after use.",
    width: "",
    height: "",
    weight: "",
    length: "",
    package: "",
  },
];
